### ISSUE TITLE
Keeping same book page when switching single-to-double

### ISSUE THREAD

**Issue by m-dp** [foobnix/LibreraReader#23] opened 2017-09-16 12:45 UTC
When switching from single page to double page mode, - for example - page 20 of 300 becomes page 20 of 150, 
but the two "page 20" are not the same book page. 
When switching and while at page 20 of 300, the current page should become 10 of 150 - to keep the same book page

**Comment by foobnix** [comment] 2018-03-09 09:40
I know about this problem and think how to fix it. 
The problem is I can't save the place of line or word to restore it with new font size

**Comment by foobnix** [comment] 2019-05-22 08:31
fixed in the [beta.librera.mobi](url)

**Closed by foobnix** 2019-05-22 08:31 UTC
