### ISSUE TITLE
Critical error Version 8.9.5-fdroid (5426) suggested Added on 2023-04-27

### ISSUE THREAD

**Issue by Skretch1974** [foobnix/LibreraReader#1109] opened 2023-04-30 07:18 UTC
Hi. After the last software update (Version 8.8.107-fdroid (5366) - Added on 2023-04-17) from the F-Droid repository, the program no longer runs and does not work at all. Reinstalling did not help. I had to reinstall previous version (Version 8.8.107-fdroid (5366) - Added on 2023-04-17). Phone with Android 12.1 arm64-v8a

**Comment by antenore** [comment] 2023-04-30 07:24
Same for me

**Comment by resoli** [comment] 2023-04-30 08:39
See #1105, #1106, #1107

**Comment by RymdLord** [comment] 2023-04-30 09:00
Same here!

**Comment by RoestVrijStaal** [comment] 2023-04-30 17:54
Just install the new version (8.9.12) in the GitHub Releases of this repository and you're good to go again. (You might be required to uninstall the previous version)

Isn't this the right moment for LibreraReader to have its own repository for serving it's APKs of GitHub Releases to F-Droid clients, instead of the slow and unreliable "official F-Droid repository"?

**Comment by Zocker1999NET** [comment] 2023-05-02 09:30
> Isn't this the right moment for LibreraReader to have its own repository for serving it's APKs of GitHub Releases to F-Droid clients, instead of the slow and unreliable "official F-Droid repository"?

Additionally, yes please, but instead, I would say no. F-Droid allows to be a central place for "mostly trustworthy" APKs to find new apps similar to the Google Play Store. Of course it takes its time for new app versions to be available their, but that's mostly due to them building the APKs themselves again instead of just trusting the APKs of the devs.

Of course, it would be great if Librera has the resources for their own repository so it becomes easier to get faster updates (and probably even dev versions). But including more repositories into your F-Droid client comes with the risk that if at least one of those repositories gets hacked, someone may be able to trick you into downloading malware (especially with F-Droid auto updates enabled).

And for me personally, trusting just a few repositories feels more secure, than trusting one  for each of my apps.

PS: The F-Droid client supports ignoring just the most recent version (for cases like this one), so auto update does not kick in and installs the failed version again, but does install the next version when it comes online: go in F-Droid to the Librera page > press the 3 dots in the upper right corner > "Ignore this update".

**Comment by trizen** [comment] 2023-05-02 11:16
Debug log (Android 7.1.1):

```
FATAL EXCEPTION: main
Process: com.foobnix.pro.pdf.reader, PID: 2671
java.lang.UnsatisfiedLinkError: No implementation found for int org.ebookdroid.droids.mupdf.codec.MuPdfDocument.getMupdfVersion() (tried Java_org_ebookdroid_droids_mupdf_codec_MuPdfDocument_getMupdfVersion and Java_org_ebookdroid_droids_mupdf_codec_MuPdfDocument_getMupdfVersion__)
	at org.ebookdroid.droids.mupdf.codec.MuPdfDocument.getMupdfVersion(Native Method)
	at com.foobnix.pdf.info.AppsConfig.<clinit>(AppsConfig.java:51)
	at com.foobnix.pdf.info.AppsConfig.loadEngine(AppsConfig.java)
	at com.foobnix.LibreraApp.onCreate(LibreraApp.java:54)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1046)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5586)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1625)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6339)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
```

**Comment by resoli** [comment] 2023-05-02 11:50
> And for me personally, trusting just a few repositories feels more secure, than trusting one for each of my apps.

I agree completely
 
> PS: The F-Droid client supports ignoring just the most recent version (for cases like this one), so auto update does not kick in and installs the failed version again, but does install the next version when it comes online: go in F-Droid to the Librera page > press the 3 dots in the upper right corner > "Ignore this update".

Very handy, thanks for this hint!

**Comment by riveravaldez** [comment] 2023-05-03 18:59
Hi, problem seems fixed on F-Droid version `8.9.12-fdroid (5458)` added on 2023-05-02. Hope it's the same for everybody.
Regards!

**Comment by antenore** [comment] 2023-05-03 19:32
I've installed the pro version to support the project.
What I'll lose or gain if I'll use the f-droid version?

I'd like to test the f-droid version to see if the problem is solved

**Comment by riveravaldez** [comment] 2023-05-03 21:32
@antenore , hi, if by chance you have Shelter or an active Work Profile, I suppose you could install it there and avoid confusions.
I don't know what could happen if you try to install both versions on the same profile, sorry.

**Comment by hackerb9** [comment] 2023-05-04 06:26
Version 8.9.12 is out on fdroid and works.

**Closed** 2023-05-16 14:27 UTC
